#!/usr/bin/env python
"""
Single-scene comparison sweep: ESFM (Moran et al., ICCV 2021, official repo) vs.
U-ESFM (this repo) on the Olsson dataset, calibrated (Euclidean) setting.
Implements Phase 1 of SPEC_single_scene_experiments.md.

Fairness ground rules enforced here:
  * identical inputs: both methods read the same shared datasets/Euclidean/<scene>.npz
    (symlinked into both repos from u-esfm/datasets/Euclidean);
  * identical post-processing: BOTH methods run WITHOUT bundle adjustment
    (ba.run_ba = false); a shared BA can be applied later by evaluate_single_scene.py
    to both methods' raw cameras, and is reported separately;
  * identical budgets: same epochs / eval intervals / lr schedule for both methods;
  * sequential execution: runs never share a GPU (one subprocess at a time per worker);
    for each (scene, seed) the two methods run back-to-back on the same GPU;
  * seeds: each (method, scene, seed) is a separate run with the seed in the conf.

Layout (all under --results-root, default <this repo>/code/results/single_scene):
  <method>/<scene_slug>/seed<k>/
      log.txt           full stdout+stderr of the run
      run.conf          exact config used
      run_meta.json     status, timing, command line, host/GPU
      raw/              the method's own outputs (metrics xlsx, cameras npz, ...)

Resumable: a run whose run_meta.json says status=completed and whose cameras npz
exists is skipped. Fail-soft: a crashed run is recorded and the sweep continues.
"""
import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
from datetime import datetime

CODE_DIR = os.path.dirname(os.path.abspath(__file__))
UESFM_REPO = os.path.dirname(CODE_DIR)
PROJECT_ROOT = os.path.dirname(UESFM_REPO)
ESFM_REPO = os.path.join(PROJECT_ROOT, 'esfm-baseline')
DATASETS_EUC = os.path.join(UESFM_REPO, 'datasets', 'Euclidean')

PYTHON = os.path.join(UESFM_REPO, '.venv', 'bin', 'python')

METHODS = ('esfm', 'esfm_rc', 'uesfm', 'uesfm_abl')

# The 36 Olsson scenes released with ESFM (datasets/Euclidean), i.e. the conf's
# scans_list minus the three DTU scenes (dtu106/dtu500/dtu700, not Olsson).
OLSSON_SCENES = [
    "Alcatraz Courtyard", "Alcatraz Water Tower", "Buddah Tooth Relic Temple Singapore",
    "Doge Palace Venice", "Door Lund", "Drinking Fountain Somewhere In Zurich",
    "East Indiaman Goteborg", "Ecole Superior De Guerre", "Eglise du dome",
    "Folke Filbyter", "Fort Channing Gate Singapore", "Golden Statue Somewhere In Hong Kong",
    "Gustav Vasa", "GustavIIAdolf", "Jonas Ahlstromer", "Kings College University Of Toronto",
    "Lund University Sphinx", "Nijo Castle Gate", "Pantheon Paris", "Park Gate Clermont Ferrand",
    "Plaza De Armas Santiago", "Porta San Donato Bologna", "Round Church Cambridge",
    "Skansen Kronan Gothenburg", "Smolny Cathedral St Petersburg", "Some Cathedral In Barcelona",
    "Sri Mariamman Singapore", "Sri Thendayuthapani Singapore", "Sri Veeramakaliamman Singapore",
    "Statue Of Liberty", "The Pumpkin", "Thian Hook Keng Temple Singapore",
    "Tsar Nikolai I", "Urban II", "Vercingetorix", "Yueh Hai Ching Temple Singapore",
]


def slug(scene):
    return scene.replace(' ', '_')


# --------------------------------------------------------------------------
# Config generation. Budgets/schedule are IDENTICAL for both methods; only the
# method-specific parts differ (model head, loss, output_mode).
# --------------------------------------------------------------------------

ESFM_CONF = """\
# Auto-generated by run_single_scene_sweep.py — ESFM baseline (official repo),
# published Optimization_Euc.conf values; BA disabled (shared BA applied later).
exp_name = single_scene_esfm
random_seed = {seed}
dataset
{{
    use_gt = False
    calibrated = True
    scan = {scene}
}}
model
{{
    type = SetOfSet.SetOfSetNet
    num_features = 256
    num_blocks = 1
    block_size = 3
    use_skip = False
    multires = 0
}}
train
{{
    lr = 1e-4
    num_of_epochs = {epochs}
    scheduler_milestone = {milestones}
    gamma = 0.1
    eval_intervals = {eval_intervals}
    sequential = {sequential}
    sequential_final_epochs = {seq_final_epochs}
}}
loss
{{
    func = ESFMLoss
    infinity_pts_margin = 1e-4
    normalize_grad = True
    hinge_loss = True
    hinge_loss_weight = 1
}}
ba
{{
    run_ba = False
    repeat = True
    triangulation = False
    only_last_eval = True
}}
"""

UESFM_CONF = """\
# Auto-generated by run_single_scene_sweep.py — U-ESFM single-scene optimization.
# Model/loss mirror confs/multiscene_uesfm_adaptive.conf (the report's method) at
# ESFM's single-scene capacity (1x3); budget/schedule identical to the ESFM arm.
exp_name = single_scene_uesfm_{scene_slug}_seed{seed}
results_path = "{raw_dir}"
num_iter = 1
random_seed = {seed}
num_jobs = 1
num_gpus = 1
general
{{
    stage = "1"
}}
dataset
{{
    dataset = "Euclidean"
    use_gt = False
    calibrated = True
    remove_outliers_gt = False
    scan = "{scene}"
}}
model
{{
    type = "SetOfSet.SetOfSetOutliersNet"
    num_features = 256
    num_blocks = 1
    block_size = 3
    use_skip = False
    multires = 0
    use_progressive = False
    use_layer_norm = True
    use_residual = True
    dropout_rate = 0.1
}}
train
{{
    lr = 1e-4
    num_epochs = {epochs}
    scheduler_milestone = {milestones}
    gamma = 0.1
    eval_intervals = {eval_intervals}
    sequential = {sequential}
    early_stopping_patience = 0
    output_mode = 3  # camera/point heads + outlier detector
    validation_metric = ["our_repro"]
    validation_metric_higher_is_better = False
    validation_metric_fine_tuning = ["our_repro"]
    extract_reproj_errors = False  # stage-2 input dump not needed; keeps timing clean
}}
loss
{{
    func = CombinedLoss          # alpha*ESFMLoss + beta*confident-pseudo-label BCE
    func_tuning = ESFMLoss
    reproj_weighting = {reproj_weighting}  # none|weighted|weighted_detach (report sec 2.2.2)

    reproj_loss_weight = 1.0
    classification_loss_weight = 0.3

    infinity_pts_margin = 1e-4
    normalize_grad = True
    hinge_loss = True
    hinge_loss_weight = 1

    inlier_percentile = {inlier_pct}
    outlier_percentile = {outlier_pct}
    min_confident_samples = 10
    min_threshold_separation = 0.0
    warmup_epochs = 10

    enable_csv_logging = False
}}
test
{{
    outliers_threshold = 0.6
}}
ba
{{
    run_ba = False
    repeat = True
    triangulation = False
    only_last_eval = True
    filter_outliers = 5.0
}}
"""


ESFM_RC_CONF = """\
# Auto-generated by run_single_scene_sweep.py — ESFM baseline run through the
# RESfM-lineage code (this repo). Mirrors the pristine RESfM release's single-scene
# conf (resfm-main-orig confs_esfm_with_outliers: SetOfSetOutliersNet with
# output_mode=1 + ESFMLoss). layer-norm/residual/dropout are u-esfm additions that
# default ON, so they are explicitly disabled here to match the RESfM release's
# model (no such layers). BA disabled (shared BA applied by the evaluator).
exp_name = single_scene_esfmrc_{scene_slug}_seed{seed}
results_path = "{raw_dir}"
num_iter = 1
random_seed = {seed}
num_jobs = 1
num_gpus = 1
general
{{
    stage = "1"
}}
dataset
{{
    dataset = "Euclidean"
    use_gt = False
    calibrated = True
    remove_outliers_gt = False
    scan = "{scene}"
}}
model
{{
    type = "SetOfSet.SetOfSetOutliersNet"
    num_features = 256
    num_blocks = 1
    block_size = 3
    use_skip = False
    multires = 0
    use_progressive = False
    use_layer_norm = False
    use_residual = False
    dropout_rate = 0.0
}}
train
{{
    lr = 1e-4
    num_epochs = {epochs}
    scheduler_milestone = {milestones}
    gamma = 0.1
    eval_intervals = {eval_intervals}
    early_stopping_patience = 0
    output_mode = 1  # ESFM behavior: camera/point heads only
    validation_metric = ["our_repro"]
    validation_metric_higher_is_better = False
    validation_metric_fine_tuning = ["our_repro"]
    extract_reproj_errors = False
}}
loss
{{
    func = ESFMLoss
    func_tuning = ESFMLoss
    infinity_pts_margin = 1e-4
    normalize_grad = True
    hinge_loss = True
    hinge_loss_weight = 1
}}
test
{{
    outliers_threshold = 0.6
}}
ba
{{
    run_ba = False
    repeat = True
    triangulation = False
    only_last_eval = True
    filter_outliers = 5.0
}}
"""


UESFM_ABL_CONF = """\
# Auto-generated by run_single_scene_sweep.py — loss ablation: U-ESFM's architecture
# (SetOfSetOutliersNet 1x3 with layer-norm/residual/dropout, as in the uesfm arm)
# trained with plain ESFMLoss / output_mode=1. Differs from the uesfm arm ONLY in
# the loss/outlier handling, and from the esfm_rc arm ONLY in the three architecture
# flags — together they factor the U-ESFM-vs-ESFM gap into loss vs architecture.
exp_name = single_scene_uesfmabl_{scene_slug}_seed{seed}
results_path = "{raw_dir}"
num_iter = 1
random_seed = {seed}
num_jobs = 1
num_gpus = 1
general
{{
    stage = "1"
}}
dataset
{{
    dataset = "Euclidean"
    use_gt = False
    calibrated = True
    remove_outliers_gt = False
    scan = "{scene}"
}}
model
{{
    type = "SetOfSet.SetOfSetOutliersNet"
    num_features = 256
    num_blocks = 1
    block_size = 3
    use_skip = False
    multires = 0
    use_progressive = False
    use_layer_norm = True
    use_residual = True
    dropout_rate = 0.1
}}
train
{{
    lr = 1e-4
    num_epochs = {epochs}
    scheduler_milestone = {milestones}
    gamma = 0.1
    eval_intervals = {eval_intervals}
    early_stopping_patience = 0
    output_mode = 1  # ESFM behavior: camera/point heads only
    validation_metric = ["our_repro"]
    validation_metric_higher_is_better = False
    validation_metric_fine_tuning = ["our_repro"]
    extract_reproj_errors = False
}}
loss
{{
    func = ESFMLoss
    func_tuning = ESFMLoss
    infinity_pts_margin = 1e-4
    normalize_grad = True
    hinge_loss = True
    hinge_loss_weight = 1
}}
test
{{
    outliers_threshold = 0.6
}}
ba
{{
    run_ba = False
    repeat = True
    triangulation = False
    only_last_eval = True
    filter_outliers = 5.0
}}
"""


def default_milestones(epochs):
    # ESFM's published schedule is [50k, 70k, 90k] for 100k epochs; scale
    # proportionally for other budgets (e.g. smoke tests).
    return [int(epochs * f) for f in (0.5, 0.7, 0.9)]


def gen_conf(method, scene, seed, epochs, eval_intervals, raw_dir,
             inlier_pct=20.0, outlier_pct=80.0, reproj_weighting='none',
             sequential=False, seq_final_epochs=20000):
    milestones = '[{}]'.format(', '.join(str(m) for m in default_milestones(epochs)))
    seq = 'true' if sequential else 'false'
    if method == 'esfm':
        return ESFM_CONF.format(seed=seed, scene=scene, epochs=epochs,
                                milestones=milestones, eval_intervals=eval_intervals,
                                sequential=seq, seq_final_epochs=seq_final_epochs)
    template = {'esfm_rc': ESFM_RC_CONF, 'uesfm_abl': UESFM_ABL_CONF}.get(method, UESFM_CONF)
    return template.format(seed=seed, scene=scene, scene_slug=slug(scene),
                           epochs=epochs, milestones=milestones,
                           eval_intervals=eval_intervals, raw_dir=raw_dir,
                           inlier_pct=inlier_pct, outlier_pct=outlier_pct,
                           reproj_weighting=reproj_weighting, sequential=seq,
                           seq_final_epochs=seq_final_epochs)


# --------------------------------------------------------------------------
# Per-run artifact locations
# --------------------------------------------------------------------------

def run_dir_for(results_root, method, scene, seed):
    return os.path.join(results_root, method, slug(scene), 'seed{}'.format(seed))


def cameras_npz(run_dir, method, scene):
    if method == 'esfm' or method.startswith('esfm_seq'):
        return os.path.join(run_dir, 'raw', 'Final_Cameras.npz')
    return os.path.join(run_dir, 'raw', 'forFigures', '{}_Final_Cameras.npz'.format(scene))


def metrics_file(run_dir, method):
    if method == 'esfm' or method.startswith('esfm_seq'):
        return os.path.join(run_dir, 'raw', 'Results_OPTIMIZATION.xlsx')
    return os.path.join(run_dir, 'raw', 'Results_OPTIMIZATION_stage_1_single_scene_bench.xlsx')


def is_completed(run_dir, method, scene, epochs=None):
    meta_path = os.path.join(run_dir, 'run_meta.json')
    if not os.path.exists(meta_path):
        return False
    try:
        with open(meta_path) as f:
            meta = json.load(f)
    except Exception:
        return False
    if epochs is not None and meta.get('epochs') != epochs:
        # a run at a different budget (e.g. a smoke test) does not count
        return False
    return (meta.get('status') == 'completed'
            and os.path.exists(cameras_npz(run_dir, method, scene))
            and os.path.exists(metrics_file(run_dir, method)))


def gpu_info():
    try:
        out = subprocess.run(['nvidia-smi', '--query-gpu=name,driver_version,memory.total',
                              '--format=csv,noheader'], capture_output=True, text=True, timeout=30)
        return out.stdout.strip()
    except Exception as e:
        return 'unavailable: {}'.format(e)


# --------------------------------------------------------------------------
# Running one (method, scene, seed)
# --------------------------------------------------------------------------

def launch_one(method, scene, seed, epochs, eval_intervals, results_root, gpu_env=None,
               alias=None, inlier_pct=20.0, outlier_pct=80.0, reproj_weighting='none',
               sequential=False, seq_final_epochs=20000):
    # alias: store results under a different method name (loss-threshold probe runs,
    # e.g. uesfm with percentiles 10/90 recorded as method 'uesfm_p1090'; esfm with
    # sequential recorded as 'esfm_seq').
    eff = alias or method
    run_dir = run_dir_for(results_root, eff, scene, seed)
    raw_dir = os.path.join(run_dir, 'raw')
    os.makedirs(raw_dir, exist_ok=True)

    conf_text = gen_conf(method, scene, seed, epochs, eval_intervals, raw_dir,
                         inlier_pct=inlier_pct, outlier_pct=outlier_pct,
                         reproj_weighting=reproj_weighting, sequential=sequential,
                         seq_final_epochs=seq_final_epochs)
    conf_name = 'ss_{}_{}_seed{}.conf'.format(eff, slug(scene), seed)

    if method == 'esfm':
        repo_code = os.path.join(ESFM_REPO, 'code')
        # include eff so an aliased run (e.g. esfm_seq) writes to its own ESFM-side
        # results dir and doesn't collide with the standard esfm run
        exp_version = '{}_{}_seed{}'.format(eff, slug(scene), seed)
    else:
        repo_code = CODE_DIR
        exp_version = None

    gen_dir = os.path.join(repo_code, 'confs', 'single_scene_generated')
    os.makedirs(gen_dir, exist_ok=True)
    conf_path = os.path.join(gen_dir, conf_name)
    with open(conf_path, 'w') as f:
        f.write(conf_text)
    shutil.copyfile(conf_path, os.path.join(run_dir, 'run.conf'))

    if method == 'esfm':
        # ESFM's path_to_conf() prepends 'confs/' itself.
        rel_conf = os.path.join('single_scene_generated', conf_name)
        cmd = [PYTHON, 'single_scene_optimization.py', '--conf', rel_conf,
               '--exp_version', exp_version]
    else:
        # u-esfm's init_exp takes the conf as a literal path relative to code/.
        rel_conf = os.path.join('confs', 'single_scene_generated', conf_name)
        cmd = [PYTHON, 'single_scene_optimization.py', '--conf', rel_conf,
               '--wandb', '0', '--stage', '1',
               '--architecture_type', 'single_scene_bench',
               '--results_aggregation_file', os.path.join(raw_dir, 'aggregated_results.xlsx')]

    env = os.environ.copy()
    env['PYTHONHASHSEED'] = '0'
    if method in ('uesfm', 'esfm_rc', 'uesfm_abl'):
        # fairness: time the in-repo arms with the same async CUDA launches as the
        # official ESFM baseline (single_scene_optimization.py honors this override)
        env['CUDA_LAUNCH_BLOCKING'] = '0'
    if gpu_env:
        env.update(gpu_env)

    meta = {
        'method': eff, 'scene': scene, 'seed': seed,
        'loss_percentiles': [inlier_pct, outlier_pct],
        'reproj_weighting': reproj_weighting,
        'epochs': epochs, 'eval_intervals': eval_intervals,
        'cmd': cmd, 'cwd': repo_code,
        'host': socket.gethostname(), 'gpu': gpu_info(),
        'start': datetime.now().isoformat(timespec='seconds'),
        'status': 'running',
    }
    meta_path = os.path.join(run_dir, 'run_meta.json')
    with open(meta_path, 'w') as f:
        json.dump(meta, f, indent=2)

    log_path = os.path.join(run_dir, 'log.txt')
    t0 = time.monotonic()
    with open(log_path, 'w') as log:
        log.write('# cmd: {}\n# cwd: {}\n\n'.format(' '.join(cmd), repo_code))
        log.flush()
        proc = subprocess.run(cmd, cwd=repo_code, env=env, stdout=log,
                              stderr=subprocess.STDOUT)
    wall = time.monotonic() - t0

    meta['end'] = datetime.now().isoformat(timespec='seconds')
    meta['wall_clock_s'] = round(wall, 2)
    meta['exit_code'] = proc.returncode

    if method == 'esfm' and proc.returncode == 0:
        # ESFM writes into its own results tree; copy the artifacts into raw/.
        src = os.path.join(ESFM_REPO, 'results', 'single_scene_esfm', exp_version)
        try:
            shutil.copyfile(os.path.join(src, 'Results_OPTIMIZATION.xlsx'),
                            os.path.join(raw_dir, 'Results_OPTIMIZATION.xlsx'))
            shutil.copyfile(os.path.join(src, 'OPTIMIZATION', scene, 'cameras', 'Final_Cameras.npz'),
                            os.path.join(raw_dir, 'Final_Cameras.npz'))
            meta['esfm_raw_results_dir'] = src
        except Exception as e:
            meta['artifact_copy_error'] = str(e)

    ok = (proc.returncode == 0
          and os.path.exists(cameras_npz(run_dir, method, scene))
          and os.path.exists(metrics_file(run_dir, method)))
    meta['status'] = 'completed' if ok else 'failed'
    with open(meta_path, 'w') as f:
        json.dump(meta, f, indent=2)
    return meta


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--scenes', default=None,
                    help='comma-separated scene names or slugs (default: all 36 Olsson scenes)')
    ap.add_argument('--methods', default='esfm,uesfm')
    ap.add_argument('--seeds', default='0,1,2')
    ap.add_argument('--epochs', type=int, default=100000)
    ap.add_argument('--eval-intervals', type=int, default=5000)
    ap.add_argument('--results-root', default=os.path.join(CODE_DIR, 'results', 'single_scene'))
    ap.add_argument('--method-alias', default=None,
                    help='store uesfm runs under this method name (loss-threshold probe)')
    ap.add_argument('--uesfm-inlier-pct', type=float, default=20.0)
    ap.add_argument('--uesfm-outlier-pct', type=float, default=80.0)
    ap.add_argument('--reproj-weighting', default='none',
                    choices=['none', 'weighted', 'weighted_detach'],
                    help='CombinedLoss reprojection weighting (report sec 2.2.2)')
    ap.add_argument('--sequential', action='store_true',
                    help='sequential-optimization fallback (ESFM paper Table 8): warm-start '
                         'on greedily-grown image subsets before the full optimization')
    ap.add_argument('--sequential-final-epochs', type=int, default=20000,
                    help='epochs for the final full-scene stage of sequential optimization '
                         '(ESFM default 20000; diagnostic: 100000 to match the standard budget)')
    ap.add_argument('--dry-run', action='store_true', help='print planned runs and exit')
    args = ap.parse_args()

    if args.scenes:
        wanted = [s.strip() for s in args.scenes.split(',') if s.strip()]
        by_slug = {slug(s): s for s in OLSSON_SCENES}
        scenes = []
        for w in wanted:
            if w in OLSSON_SCENES:
                scenes.append(w)
            elif w in by_slug:
                scenes.append(by_slug[w])
            else:
                sys.exit('Unknown scene: {!r}'.format(w))
    else:
        scenes = list(OLSSON_SCENES)

    methods = [m.strip() for m in args.methods.split(',') if m.strip()]
    for m in methods:
        if m not in METHODS:
            sys.exit('Unknown method: {!r} (expected esfm/esfm_rc/uesfm/uesfm_abl)'.format(m))
    seeds = [int(s) for s in args.seeds.split(',') if s.strip() != '']

    # sanity: shared dataset must exist for every scene
    missing = [s for s in scenes if not os.path.exists(os.path.join(DATASETS_EUC, s + '.npz'))]
    if missing:
        sys.exit('Missing dataset npz for: {}'.format(missing))

    # Method order is fixed inside each (scene, seed) so both methods run
    # back-to-back on the same GPU (fair runtime comparison).
    plan = [(scene, seed, method) for scene in scenes for seed in seeds for method in methods]

    print('Planned runs: {} ({} scenes x {} seeds x {} methods)'.format(
        len(plan), len(scenes), len(seeds), len(methods)))
    if args.dry_run:
        for scene, seed, method in plan:
            eff = args.method_alias or method
            state = 'DONE' if is_completed(run_dir_for(args.results_root, eff, scene, seed), eff, scene, args.epochs) else 'todo'
            print('  [{}] {:6s} seed{} {}'.format(state, eff, seed, scene))
        return

    failures, skipped, completed = [], 0, 0
    for i, (scene, seed, method) in enumerate(plan, 1):
        eff = args.method_alias or method
        run_dir = run_dir_for(args.results_root, eff, scene, seed)
        if is_completed(run_dir, eff, scene, args.epochs):
            print('[{}/{}] SKIP (done) {} seed{} {}'.format(i, len(plan), eff, seed, scene), flush=True)
            skipped += 1
            continue
        print('[{}/{}] RUN {} seed{} {} (epochs={})'.format(
            i, len(plan), eff, seed, scene, args.epochs), flush=True)
        try:
            meta = launch_one(method, scene, seed, args.epochs, args.eval_intervals,
                              args.results_root,
                              alias=args.method_alias,
                              inlier_pct=args.uesfm_inlier_pct,
                              outlier_pct=args.uesfm_outlier_pct,
                              reproj_weighting=args.reproj_weighting,
                              sequential=args.sequential,
                              seq_final_epochs=args.sequential_final_epochs)
        except Exception as e:
            meta = {'method': method, 'scene': scene, 'seed': seed,
                    'status': 'failed', 'runner_error': str(e)}
        if meta.get('status') == 'completed':
            completed += 1
            print('    completed in {}s'.format(meta.get('wall_clock_s')), flush=True)
        else:
            failures.append(meta)
            print('    FAILED (exit={}, see {})'.format(
                meta.get('exit_code'), os.path.join(run_dir, 'log.txt')), flush=True)

    print('\n===== sweep summary =====')
    print('completed: {}  skipped(already done): {}  failed: {}'.format(completed, skipped, len(failures)))
    for f in failures:
        print('  FAILED: {} seed{} {} (exit={})'.format(
            f.get('method'), f.get('seed'), f.get('scene'), f.get('exit_code')))
    if failures:
        sys.exit(1)


if __name__ == '__main__':
    main()
